# Travis integration for running unittests on pupil-labs/pupil

# NOTE: Tests are currently only ran on Ubuntu 18.04
# There's a docker image pupillabs/pupil-docker-ubuntu:latest which contains all
# required dependencies for the test-suite to run.

os: minimal
services: docker

before_install:
  - docker pull pupillabs/pupil-docker-ubuntu:latest
  - chmod +x ./.travis/*.sh

script:
  - >
    docker run --rm
    -v `pwd`:/repo
    -w /repo
    pupillabs/pupil-docker-ubuntu:latest
    /bin/bash /repo/.travis/run_tests.sh
